### ISSUE TITLE
prisma-multi-tenant init throw error 

### ISSUE THREAD

**Issue by denisp107** [Errorname/prisma-multi-tenant#11]
I got below error when I run `prisma-multi-tenant init`

error: Environment variable not found: PMT_URL.
  -->  schema.prisma:5
   | 
 4 |   provider = "mysql"
 5 |   url      = env("PMT_URL")

**Comment by Errorname** [comment]
Hi! Can you run "prisma-multi-tenant init --verbose" on your project and show the full logs ? Thanks 🙏

**Comment by denisp107** [comment]
Can you please make an example project for multi-tanent? Backend(typescript) and frontend(react) preferred
