### ISSUE TITLE
Update prisma-multi-tenant new command

### ISSUE THREAD

**Issue by denisp107** [Errorname/prisma-multi-tenant#12]
Please update the command `prisma-multi-tenant new`
Currently we are building slack like app. 
So, we're finding the solution for creating tenant by calling the rest api on the frontend side. 

We are going to run the `prisma-multi-tenant new` command using `const { exec } = require('child_process');`
But we are not able to input tenant name and database url which is asked by `prisma-multi-tenant new` command.

So, please make the argument option like this 
`prisma-multi-tenant new -name='tenant1' -databaseurl='postgresql://postgres:postgres@localhost:5432/xxxxx'`

Thanks

**Comment by Errorname** [comment]
Hi, there is already a solution to provide the name and url of the tenant:
```
prisma-multi-tenant new --name=the_name --url=postgresql://...
```

To learn more about the options, you can run `prisma-multi-tenant new --help` 🙂 

---

Note: Instead of running prisma-multi-tenant new with `exec`, maybe I can provide a management interface that would look something like that:

```js
const { Management } = require('prisma-multi-tenant')

const management = new Management()

management.newTenant({
  name: 'the_name',
  url: 'postgresql://...'
})
```

Would this solution be good for you ?

**Comment by denisp107** [comment]
```
const { Management } = require('prisma-multi-tenant')

const management = new Management()

management.newTenant({
  name: 'the_name',
  url: 'postgresql://...'
})
```

This solution works for me.
btw, `prisma-multi-tenant new --name=the_name --url=postgresql://...` still ask `Are you sure of your inputs?`, so I can't use it

**Comment by Errorname** [comment]
> btw, prisma-multi-tenant new --name=the_name --url=postgresql://... still ask Are you sure of your inputs?, so I can't use it

Oh indeed, I'll fix this bug

**Comment by denisp107** [comment]
Can you add me to your slack?

**Comment by Errorname** [comment]
I don't have a personal Slack, but we can use Prisma's Slack (https://prisma.slack.com). My username is Errorname

**Comment by denisp107** [comment]
what is your skype?

**Comment by Errorname** [comment]
I don't have skype either, twitter ?

**Comment by Errorname** [comment]
The latest alpha version (2.0.0-alpha10) now allows you to create and delete tenants (See [documentation](https://github.com/Errorname/prisma-multi-tenant/blob/master/docs/Complete_Documentation.md#createtenanttenant--name-string-provider-string-url-string--options-any-promisephoton))

Here is a code example:
```js
const { MultiTenant } = require('prisma-multi-tenant')

const multiTenant = new MultiTenant()

await multiTenant.createTenant({
  name: "my_tenant",
  provider: "postgresql",
  url: "postgres://..."
})
```

**Comment by Errorname** [comment]
The latest version also fixes the `prisma-multi-tenant new --name=abc --url=something` bug, so I'll close this issue
