### ISSUE TITLE
prisma-multi-tenant dev <name> 

### ISSUE THREAD

**Issue by denisp107** [Errorname/prisma-multi-tenant#13]
If we have 10 tenants, should we run this command 10 times on the server?
If we have unlimited tenants similar slack?

**Comment by Errorname** [comment]
The `prisma-multi-tenant dev <name>` command is a wrapper of the `prisma2 dev` command.

The `prisma2 dev` command is only to be used while in development. When you are satisfied with the state of your schema, you will have to save the migration (`prisma-multi-tenant env <name> -- prisma2 lift save` for now, but soon `prisma-multi-tenant lift save`)

Once you have the migration saved, you only have to run `prisma-multi-tenant lift up` to lift all the tenants and there you have it 🙂 

(To learn more about the dev flow, you can read the [Getting Started](https://github.com/Errorname/prisma-multi-tenant/blob/master/docs/Getting_Started.md) documentation)
