### ISSUE TITLE
Introduce command to create management DB

### ISSUE THREAD

**Issue by BjoernRave** [Errorname/prisma-multi-tenant#15]
When bringing my already initialized repo to another database, I need to do `prisma-multi-tenant lift management up -- --create-db` first, so the management db gets automatically created and initialized.

It would be nice to have a command for this, maybe along the lines of:
`prisma-multi-tenant new management`

I think it's maybe also a good idea to make it more present to the user, that `management` is a reserved name, so that no issues appear in that regard

**Comment by Errorname** [comment]
Thanks for the issue 🙏 

This command has been implemented and shipped in Alpha22.1
