### ISSUE TITLE
Improve Error-handling 

### ISSUE THREAD

**Issue by BjoernRave** [Errorname/prisma-multi-tenant#16]
It would be good if errors coming from prisma, while used by prisma-multi-tenant would be "passed through" to the users.

Also adding the `debug` parameter when instantiating Prisma-multi-tenant like it is done with prisma would be cool, for easier debugging:

`const multitenant = new MultiTenant<Photon>({ Photon, PhotonManagement, debug: true })`

**Comment by Errorname** [comment]
Thanks for the issue 🙏 

This has been implemented and shipped in Alpha22.1
