### ISSUE TITLE
Implement a method to check if a tenant exists

### ISSUE THREAD

**Issue by BjoernRave** [Errorname/prisma-multi-tenant#20]
Currently when I want to check if a tenant already exists I need to wrap the `.get` function in a trycatch block, because it will throw, when it can't find a tenant. 

It would be nice to have a cleaner way to check if a tenant already exists

**Comment by Errorname** [comment]
`prisma-multi-tenant@2.0.0-alpha19` now implements an `.existsTenant(name: string): Promise<Boolean>` method to check if a tenant exists in the management
