### ISSUE TITLE
Space in path name throws error on generation

### ISSUE THREAD

**Issue by Xaedblade** [Errorname/prisma-multi-tenant#22]
This is an issue for windows computers. I've run into this several times. my fix was to change my project folder name on my home pc. But my work laptop uses my name as the user with a space... so can't fix. i.e C:\Users\firstname lastname\ will throw an error because of the space in the path.

error message:
Are you sure of your inputs? Yes

Updating your schema.prisma file...

Generating prisma clients for both management and tenants...
{ Error: Command failed: C:\Users\C*** V*******\Desktop\warehouse 3\node_modules.bin/prisma2 generate
'C:\Users\C***' is not recognized as an internal or external command,
operable program or batch file.

at ChildProcess.exithandler (child_process.js:294:12)
at ChildProcess.emit (events.js:198:13)
at maybeClose (internal/child_process.js:982:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
killed: false,
code: 1,
signal: null,
cmd:
'C:\\Users\\C*** V****\\Desktop\\warehouse 3\\node_modules\\.bin/prisma2 generate ' }

**Comment by Errorname** [comment]
Thanks for raising this issue 🙏 

I can reproduce this, I'll fix this in the next release

**Comment by Xaedblade** [comment]
Thank you! That would be great 🥇

**Comment by Xaedblade** [comment]
@Errorname I can fix this if you like? I know where the issue is.

**Comment by Errorname** [comment]
Thank for offering, but I already wrote a fix. 🙂 I'm finishing the documentation for the new release and I'll publish it by the end of the day or tomorrow

**Comment by Errorname** [comment]
The latest release [alpha22](https://github.com/Errorname/prisma-multi-tenant/releases/tag/2.0.0-alpha22) should now work with folder having spaces.

Thanks again for filing this issue 🙏

**Comment by Xaedblade** [comment]
Thanks!
