### ISSUE TITLE
prisma-multi-tenant init returns ERROR: local and remote migrations are not in lockstep

### ISSUE THREAD

**Issue by Xaedblade** [Errorname/prisma-multi-tenant#23]
No matter what I do I keep getting this error

Steps to reproduce the issue:

1. First setup single tenant i.e. normal prisma2 datamodel by using prisma2 init command
2. Provide the mandatory details like datasource url (postgres database url) and execute prisma2 migrate save --name "migration-name" --experimental and prisma2 migrate up --experimental commands respectively ( It will deploy changes to the postgres database )
3. Initialize the multi-tenant using prisma-multi-tenant init command and get error below.

Error
`  Setting up management database...
Unknown Error!
{ Error: Command failed: C:\warehouse_3\node_modules\.bin/prisma2 migrate up --create-db  --experimental
Error: Local and remote migrations are not in lockstep. We have migration 20191220082006-alpha locally and 20200220145008-init remotely at the same position in the history.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'C:\\warehouse_3\\node_modules\\.bin/prisma2 migrate up --create-db  --experimental' }`

**Comment by Errorname** [comment]
Thanks for raising this issue 🙏 

It looks like you are using the same url between your tenant, and the management prompted when running `prisma-multi-tenant init`

**Comment by Xaedblade** [comment]
Thank you, I will give this a try.

**Comment by Xaedblade** [comment]
That did the trick! thanks
