### ISSUE TITLE
prisma-multi-tenant init, freezes

### ISSUE THREAD

**Issue by Dragons0458** [Errorname/prisma-multi-tenant#35]
Hello! When I try to run the ```prisma-multi-tenant init``` command the generation freezes when it tries to create the management database, would you know why this happens? Thank you!

![imagen](https://user-images.githubusercontent.com/3160847/81650466-cc71e980-93e6-11ea-89fd-bc22686e2940.png)

**Comment by Errorname** [comment]
Hi @Dragons0458 ! Did you try running `npx @prisma/cli` generate to see if there was an error ?

**Comment by Dragons0458** [comment]
Hello! i tried linux, added the path like: file:./man.db and it worked correctly: D

**Comment by Errorname** [comment]
Ah great! Indeed, it looks in the picture that there was missing a "file:" in the database url :)
I'm closing this issue then
