### ISSUE TITLE
Serverless database

### ISSUE THREAD

**Issue by gcherem** [Errorname/prisma-multi-tenant#41]
Hi! Can I use prisma-multi-tenant with a serverless database? (aurora for instance)

**Comment by Errorname** [comment]
Hi @gcherem 👋 

Unfortunately, I don't think it would work: Prisma-multi-tenant is kind of a "wrapper" of Prisma. And, as it can be seen on [this issue](https://github.com/prisma/prisma/issues/1964), Prisma doesn't work at the moment with Aurora
