### ISSUE TITLE
create tenant programatically

### ISSUE THREAD

**Issue by gcherem** [Errorname/prisma-multi-tenant#42]
Is that possible to create a tenant programatically, inside a mutation? I'd like to have a TENANTS table in a separated instance, with support to CRUD tenants. Thanks!

**Comment by Errorname** [comment]
Yes, you can create the tenants programmatically !

Here is how prisma-multi-tenant (pmt) works:
- pmt initialize your project by creating a "management" database which holds the tenants name & url
- pmt installs a "client" (@prisma-multi-tenant/client) in your project
- This client can be used to [query the Prisma instances](https://github.com/Errorname/prisma-multi-tenant/blob/master/docs/Complete_Documentation.md#getname-string-options-any-promiseprismaclient) corresponding to the tenants:
```
multiTenant.get('my_tenantA') // This returns a Prisma instance for the tenant my_tenantA
```
- This tenant can also [create and delete tenants](https://github.com/Errorname/prisma-multi-tenant/blob/master/docs/Complete_Documentation.md#createtenanttenant--name-string-url-string--options-any-promiseprismaclient):
```
multiTenant.createTenant({
  name: 'my_tenantB',
  url: 'postgresql://the_postgres_url'
})
```

Don't hesitate to read the [Getting Started Guide](https://github.com/Errorname/prisma-multi-tenant/blob/master/docs/Getting_Started.md) which introduce you to what is possible to do as well as the [complete documentation](https://github.com/Errorname/prisma-multi-tenant/blob/master/docs/Complete_Documentation.md) 🙂

**Comment by gcherem** [comment]
Thanks! 👍
