### ISSUE TITLE
Should we upgrade Prisma to the latest edition

### ISSUE THREAD

**Issue by 364734461** [Errorname/prisma-multi-tenant#59]
Should we upgrade Prisma to the latest edition

**Comment by asaadawey** [comment]
i think no , i am a newly commer to pmt . i cannot initiate it and i think this because my prisma version

**Comment by Errorname** [comment]
Hi @364734461 👋 

Upgrading to a newer Prisma version should theoretically work (@asaadawey issue looks to be something else). I intend to make a new release of prisma-multi-tenant soon to integrate newer versions of Prisma anyways.

**Comment by solinad21** [comment]
agree with this message, i can not run your component in windows 10 environment.

**Comment by Errorname** [comment]
Hi everyone! I just released the 2.4.1 version which includes prisma@2.10.1, thanks for your patience
