### ISSUE TITLE
pmt generate requires globally installed version of prisma-multi-tenant

### ISSUE THREAD

**Issue by BjoernRave** [Errorname/prisma-multi-tenant#70]
When running `pmt generate` without having `prisma-multi-tenant` installed globally via npm, the `.prisma-multi-tenant` folder does not get generated.

It would be nice if it could detect a version of `prisma-multi-tenant` installed as dev dependency and use that.

This is causing problems when trying to build inside github actions for example

**Comment by Errorname** [comment]
I think this issue has been resolved with the release of pmt @ 2.4.1. If you or someone else stil experiences this issue, don't hesitate to reopen this issue 🙏
